name: CI Demo
run-name: ${{ github.actor }} CI Demo 
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Python Setup 
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip 
          pip install -r requirements.txt
      - name: Run the main script and grep output
        run: python main.py | grep "BTCUSDT"
      
